// automatically generated by scripts/fetch-shells.mjs
// do not edit this file directly.

import log from '../log';
export interface IFoundShell<T> {
  readonly shell: T
  readonly path: string
  readonly extraArgs?: string[]
}
